/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderPostcardRouteImport } from './routes/order.postcard'
import { Route as OrderNamecardRouteImport } from './routes/order.namecard'
import { Route as OrderLeafletRouteImport } from './routes/order.leaflet'
import { Route as OrderFlyerRouteImport } from './routes/order.flyer'
import { Route as OrderBookletRouteImport } from './routes/order.booklet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPostcardRoute = OrderPostcardRouteImport.update({
  id: '/order/postcard',
  path: '/order/postcard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNamecardRoute = OrderNamecardRouteImport.update({
  id: '/order/namecard',
  path: '/order/namecard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderLeafletRoute = OrderLeafletRouteImport.update({
  id: '/order/leaflet',
  path: '/order/leaflet',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFlyerRoute = OrderFlyerRouteImport.update({
  id: '/order/flyer',
  path: '/order/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderBookletRoute = OrderBookletRouteImport.update({
  id: '/order/booklet',
  path: '/order/booklet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order/booklet': typeof OrderBookletRoute
  '/order/flyer': typeof OrderFlyerRoute
  '/order/leaflet': typeof OrderLeafletRoute
  '/order/namecard': typeof OrderNamecardRoute
  '/order/postcard': typeof OrderPostcardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order/booklet': typeof OrderBookletRoute
  '/order/flyer': typeof OrderFlyerRoute
  '/order/leaflet': typeof OrderLeafletRoute
  '/order/namecard': typeof OrderNamecardRoute
  '/order/postcard': typeof OrderPostcardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order/booklet': typeof OrderBookletRoute
  '/order/flyer': typeof OrderFlyerRoute
  '/order/leaflet': typeof OrderLeafletRoute
  '/order/namecard': typeof OrderNamecardRoute
  '/order/postcard': typeof OrderPostcardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order/booklet'
    | '/order/flyer'
    | '/order/leaflet'
    | '/order/namecard'
    | '/order/postcard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order/booklet'
    | '/order/flyer'
    | '/order/leaflet'
    | '/order/namecard'
    | '/order/postcard'
  id:
    | '__root__'
    | '/'
    | '/order/booklet'
    | '/order/flyer'
    | '/order/leaflet'
    | '/order/namecard'
    | '/order/postcard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderBookletRoute: typeof OrderBookletRoute
  OrderFlyerRoute: typeof OrderFlyerRoute
  OrderLeafletRoute: typeof OrderLeafletRoute
  OrderNamecardRoute: typeof OrderNamecardRoute
  OrderPostcardRoute: typeof OrderPostcardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/postcard': {
      id: '/order/postcard'
      path: '/order/postcard'
      fullPath: '/order/postcard'
      preLoaderRoute: typeof OrderPostcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/namecard': {
      id: '/order/namecard'
      path: '/order/namecard'
      fullPath: '/order/namecard'
      preLoaderRoute: typeof OrderNamecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/leaflet': {
      id: '/order/leaflet'
      path: '/order/leaflet'
      fullPath: '/order/leaflet'
      preLoaderRoute: typeof OrderLeafletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/flyer': {
      id: '/order/flyer'
      path: '/order/flyer'
      fullPath: '/order/flyer'
      preLoaderRoute: typeof OrderFlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/booklet': {
      id: '/order/booklet'
      path: '/order/booklet'
      fullPath: '/order/booklet'
      preLoaderRoute: typeof OrderBookletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderBookletRoute: OrderBookletRoute,
  OrderFlyerRoute: OrderFlyerRoute,
  OrderLeafletRoute: OrderLeafletRoute,
  OrderNamecardRoute: OrderNamecardRoute,
  OrderPostcardRoute: OrderPostcardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
